apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: wordpress
name: wordpress
namespace: wordpress
releaseName: wordpress
repo: oci://registry-1.docker.io/bitnamicharts
valuesFile: values.yaml